# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build api`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t api`.

FROM docker.io/node:lts-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./

RUN npm ci
COPY . .
RUN npx nx reset && npm run build

FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN apk add --no-cache openssl

RUN addgroup --system api && \
          adduser --system -G api api

COPY --from=builder /app/dist/api .
COPY package*.json ./
COPY prisma prisma
COPY startup.sh startup.sh

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm -f install

CMD ["./startup.sh"]
